root: true

extends:
  - "@whitetrefoil/eslint-config/with-type"
  # Or below instead if it's a node project
  #- "@whitetrefoil/eslint-config/with-type/node"

rules:
  no-console: 0
  "@typescript-eslint/naming-convention": 0

overrides:
  - files:
      - "scripts/*.js"

    env:
      node: true

    rules:
      "no-console": 0
